export const fields = [
  {
    id: "lote-norte",
    name: "Lote Norte",
    area: "12 ha",
    crop: "Maíz tardío",
    stage: "R5 · llenado",
    variety: "DK70-10",
    moisture: "18%",
    soil: "Franco limoso",
    irrigation: "Goteo automatizado",
    irrigationStatus: "Activo",
    tasksPending: 3,
    openAlerts: 1,
    health: 82,
    lastActivity: "Riego + ferti · 02/02",
    nextAction: "Monitoreo de cogollero",
    supervisor: "García",
    plantingDate: "10 Ene",
    harvestWindow: "15 Abr - 05 May",
    yieldTarget: "10.2 t/ha",
    notes: "Registrar monitoreo de plagas cada 48h.",
    sharedWith: [
      { id: "u1", name: "Ing. Agrónomo", avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
      { id: "u2", name: "Dueño", avatar: "https://randomuser.me/api/portraits/men/44.jpg" },
    ],
  },
  {
    id: "lote-sur",
    name: "Lote Sur",
    area: "8 ha",
    crop: "Soja de primera",
    stage: "R2 · floración",
    variety: "DM 4612",
    moisture: "22%",
    soil: "Franco arcilloso",
    irrigation: "Aspersión",
    irrigationStatus: "Programado 22:00",
    tasksPending: 2,
    openAlerts: 0,
    health: 75,
    lastActivity: "Aplicación fungicida · 31/01",
    nextAction: "Relevamiento de malezas",
    supervisor: "Sosa",
    plantingDate: "20 Dic",
    harvestWindow: "20 Abr - 10 May",
    yieldTarget: "3.2 t/ha",
    notes: "Revisar deriva en borde oeste.",
  },
  {
    id: "lote-este",
    name: "Lote Este",
    area: "5 ha",
    crop: "Trigo",
    stage: "Llenado de grano",
    variety: "Baguette 620",
    moisture: "15%",
    soil: "Franco",
    irrigation: "Secano",
    irrigationStatus: "Sin riego",
    tasksPending: 1,
    openAlerts: 0,
    health: 90,
    lastActivity: "Monitoreo sanitario · 30/01",
    nextAction: "Programar cosecha piloto",
    supervisor: "Pérez",
    plantingDate: "05 Oct",
    harvestWindow: "25 Feb - 10 Mar",
    yieldTarget: "6.8 t/ha",
    notes: "Buen stand. Confirmar humedad antes de cosechar.",
    sharedWith: [
      { id: "u3", name: "Contratista", avatar: "https://randomuser.me/api/portraits/women/68.jpg" },
    ],
  },
];

export const getFieldById = (id) => fields.find((field) => field.id === id);
